import Vue from 'vue'
import { MLInstaller, MLCreate, MLanguage } from 'vue-multilanguage'

Vue.use(MLInstaller);

export default new MLCreate({
    initial: 'russian',
    save: process.env.NODE_ENV === 'production',
    languages: [
        new MLanguage('english').create({
            for_admin: 'Task only for admin',
            approve: 'Approve',
            active_masters: 'Active masters',
            new_masters: 'New masters',
            masters: 'Masters',
            all_tasks: 'All tasks',
            types: 'Types',
            admin: 'Admin',
            add_type: 'Add type',
            close: 'Close',
            save: 'Save',
            type_name: 'Type name*',
            type_system_name: 'Type system name*',
            new_tasks: 'New tasks',
            new_task: 'New task',
            active_task: 'Active task',
            completed_task: 'Completed task',
            in_progress: 'In progress',
            done: 'Done',
            only_my: 'Only my',
            all: 'All',
            to_done: 'Done',
            delete: 'Delete',
            change: 'Change',
            type: 'Type',
            date: 'Date',
            client: 'Client',
            master: 'Master',
            to_work: 'To work',
            add_task: 'Add task',
            add_task_caps: 'ADD TASK',
            title: 'Title',
            description: 'Description',
            priority: 'Priority',
            select_file: 'Select file',
            upload: 'Upload',
            drag: 'Drag your image here',
            or: 'or',
            add_success: 'Task was added successful',
            name: 'Name',
            position: 'Position',
            active: 'Active',
            yes: 'Yes',
            no: 'No',
            new_pass: 'New password',
            pass: 'Password',
            confirm_new_pass: 'Confirm new password',
            confirm_pass: 'Confirm password',
            change_profile: 'Change profile',
            change_pass: 'Change password',
            not_match: 'Passwords do not match',
            phone: 'Phone',
            profile_success: 'Profile was saved successfully',
            pass_success: 'Password was saved successfully',
            full_name: 'Full name',
            sign_up: 'Sign up',
            sign_in: 'Sign in',
            sign_out: 'Sign out',
            profile: 'Profile',
            settings: 'Settings',
            register: 'Register',
            login: 'Login',
            home: 'GO!MISSIONS',
            reg_rule: 'To enter your account you should verify email',
            del_type: 'Do you really want to delete this task type?',
            low: 'Low',
            medium: 'Medium',
            high: 'High',
            error: 'Error!',
            success: 'Success!',
            verify: 'Email wasn\'t verified!',
            exist: 'This account doesn\'t exist!',
            forget: 'Forgot your password?',
            reset_email: 'Send password reset email',
            try_again: 'Go to the reset email page and try again.',
            created: 'Account with this email does not exist.',
        }),

        new MLanguage('russian').create({
            for_admin: 'Задания только для админа',
            approve: 'Подтвердить',
            active_masters: 'Активные мастера',
            new_masters: 'Новые мастера',
            masters: 'Мастера',
            all_tasks: 'Задания',
            types: 'Типы',
            admin: 'Админ',
            add_type: 'Добавить тип',
            close: 'Закрыть',
            save: 'Сохранить',
            type_name: 'Название типа*',
            type_system_name: 'Системное название типа*',
            new_tasks: 'Новые задания',
            new_task: 'Новое задание',
            active_task: 'Активное задание',
            completed_task: 'Выполненное задание',
            in_progress: 'В работе',
            done: 'Выполнены',
            only_my: 'Только мои',
            all: 'Все',
            to_done: 'Выполнено',
            delete: 'Удалить',
            change: 'Изменить',
            type: 'Тип',
            date: 'Дата',
            client: 'Клиент',
            master: 'Мастер',
            to_work: 'В работу',
            add_task: 'Добавить задание',
            add_task_caps: 'ДОБАВИТЬ ЗАДАНИЕ',
            title: 'Заголовок',
            description: 'Описание',
            priority: 'Приоритет',
            select_file: 'Выберите файл',
            upload: 'Загрузить',
            drag: 'Перетащите Ваше изображение сюда',
            or: 'или',
            add_success: 'Задание было успешно добавлено',
            name: 'Имя',
            position: 'Должность',
            active: 'Активный',
            yes: 'Да',
            no: 'Нет',
            new_pass: 'Новый пароль',
            pass: 'Пароль',
            confirm_new_pass: 'Подтвердите новый пароль',
            confirm_pass: 'Подтвердите пароль',
            change_profile: 'Изменить профиль',
            change_pass: 'Изменить пароль',
            not_match: 'Пароли не совпадают!',
            phone: 'Телефон',
            profile_success: 'Профиль успешно изменен',
            pass_success: 'Пароль успешно сохранен',
            full_name: 'Полное имя',
            sign_up: 'Зарегистрироваться',
            sign_in: 'Войти',
            sign_out: 'Выйти',
            profile: 'Профиль',
            settings: 'Настройки',
            register: 'Регистрация',
            login: 'Вход',
            home: 'GO!MISSIONS',
            reg_rule: 'Для входа в аккаунт Вам необходимо верифицировать e-mail',
            del_type: 'Вы действительно хотите удалить этот тип?',
            low: 'Низкий',
            medium: 'Средний',
            high: 'Высокий',
            error: 'Ошибка!',
            success: 'Успех!',
            verify: 'E-mail не был верифицирован!',
            exist: 'Такого аккаунта не существует!',
            forget: 'Забыли Ваш пароль?',
            reset_email: 'Отправить письмо для восстановления пароля',
            try_again: 'Перейдите на страницу отправки письма и попробуйте еще раз.',
            created: 'Аккаунта с этим e-mail адресом не существует.',
        })
    ]
})
